# Generated by Django 6.0.6 on 2026-06-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(default='Python,Django,SQL'),
            preserve_default=False,
        ),
    ]
