# Generated by Django 6.0.6 on 2026-06-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_application_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interview_mode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20),
        ),
    ]
