# Generated by Django 6.0.6 on 2026-06-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_application_interview_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interview_mode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
