# Generated by Django 6.0.6 on 2026-06-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_interviewresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
