# Generated by Django 6.0.6 on 2026-07-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_interviewresult_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
    ]
